# Generated by Django 2.2.6 on 2019-10-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=60)),
                ('organization', models.IntegerField(max_length=60)),
                ('issue_date', models.DateField()),
                ('link', models.TextField()),
            ],
        ),
    ]
