# Generated by Django 2.2.6 on 2019-10-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20191024_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
