# Generated by Django 2.2.6 on 2019-10-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20191025_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
